### ISSUE TITLE
[1.12.2] Inability to see patterns in crafting manager when using multiblock crafter

### ISSUE THREAD

**Issue by DannehSC** [TechReborn/RebornStorage#101]
Versions:

Whatever versions are used in Sevtech Version 3.0.8 (so sorry, I don't see the versions of the actual mods.)

Expected:

Ability to insert and see patterns inside the multiblock when using the crafter manager.

Actually happens:

Inability to insert and see patterns inside the multiblock when using the crafter manager.

**Comment by raoulvdberge** [comment]
Could you write a more detailed report please with screenshots? As this is worthless at the moment...

**Comment by DannehSC** [comment]
Sorry. Wasn't sure what kind of data you needed. lol  I'll send the data asap.

**Comment by DannehSC** [comment]
Single-player or Multi:

Multiplayer.

Multiblock crafter location:

Inside compact machine, hooked in via cables using the compact machine tunnels.

Versions:

MC: 1.12.2
Forge: 14.23.4.2707

Compact Machines 3: 1.12.2-3.0.12-b215
Reborn Core: 3.8.7.295
Reborn Storage: 3.1.0.50
Refined Storage: 1.5.34
Refined Storage Addons: 0.3

Screenshots:

https://imgur.com/a/swkJ8ki

**Comment by calloatti** [comment]
Just scroll down in the crafter manager. The sorting is currently kind of messed up and the empty slots can display first sometimes.

**Comment by DannehSC** [comment]
Even scrolling aaaall the way down, not seeing it. It was probably a bad idea to add 108 crafting storage blocks.

**Comment by raoulvdberge** [comment]
So the problem is that you can't see them in another dimension?

**Comment by DannehSC** [comment]
I guess you could call it that. I was hoping to have it in a compact machine, which would put it out of the way, but the dimension changing is a pain in SevTech. So I hoped to use the crafter manager as a.. Bypass, per say.

**Comment by raoulvdberge** [comment]
But can you see it in the same dimension as the multiblock??

**Comment by DannehSC** [comment]
I assumed since it showed up there would be no difference.. But I'll try that.

**Comment by DannehSC** [comment]
Breaking and reassembling the multiblock allows the patterns to show up in the crafter manager.. But it's in a reaaaally weird position.

**Comment by sandalle** [comment]
From what I've seen similar to this bug is if you as a player change dimensions, the multiblock Crafter stops reporting what recipes it has to Refined Storage.

To duplicate:
NOTE: This seemed to happen to me _every_ time I changed dimensions, but now when I go to reproduce it and test whether it's caused by vanilla dimensions, non-vanilla dimensions (e.g. RFTools Dimensions), vanilla teleporters (e.g. Nether Portal), or other mod teleporters (e.g. RFTools Dialing Device)...I cannot reliably replicate it. Below are the steps I feel caused it the most, if it helps. :)

1. Setup Refined Storage with a multi-block Crafter from Reborn Storage in a chunkloaded chunk in the Overworld (I have a chunkloader from https://minecraft.curseforge.com/projects/persistent-bits keeping my Refined Storage and power generation area chunk loaded).
1. Put some recipes in the multiblock Crafter and verify they are visible in the Refined Storage Crafting Grid.
1. Travel to another dimension, such as the Nether via a vanilla (Nether Portal) or non-vanilla transportation (e.g. RFTools Dialing Device is what I tested).
1. Come back to Overworld with either method above and see that your mutliblock Crafting recipes no longer show. Regular Refined Storage Crafter recipes still show.

Minecraft 1.12.2
Forge Mod Loader 1.12.2-14.23.5.2769
refinedstorage-1.6.9
refinedstorageaddons-0.4.3
RebornCore-1.12.2-3.10.4.348
RebornStorage-1.12.2-3.2.2.65

Modpack: https://minecraft.curseforge.com/projects/nst-world-of-color
