### ISSUE TITLE
[Question/Possible Bug]

### ISSUE THREAD

**Issue by Hail4Gaming** [TechReborn/RebornStorage#122]
I have a lever on my Controller for Refined Storage in the Direwolf20 1.12 pack so that I may turn it off to conserve power (early game setup)--I just built a 3CPU/3Storage Reborn Storage Autocrafter Multiblock, however when I turn off the Controller, it still draws 60fe/t power, though it should be disabled. Is there a reason it still draws power when the controller is turned off?

**Reborn Storage Version**: 3.2.2.65
**Refined Storage Version**: 1.6.4

**Comment by modmuss50** [comment]
I’m not sure, as far as I know we use the api to refined storage correctaly for power usage

**Comment by Hail4Gaming** [comment]
That is strange. I shall be on again later and I plan to try using a lever on the multiblock itself, though I doubt itll work. I was trying to see if I could find a cable piece similar to the AE Bus that allows a lever to control whether there cable is active or not-an on/off switch for the cable per-se-so I could just do it that way. Right now I just destroy and replace the cable when needed.

**Comment by raoulvdberge** [comment]
@modmuss50 

Your problem is here:

https://github.com/TechReborn/RebornStorage/blob/1.12/src/main/java/me/modmuss50/rebornstorage/tiles/CraftingNode.java#L204-L207

The system will *always* extract, no matter if the network is inactive or active by redstone setting (this to allow for flexibility to addon developers.)

The system will not extract if `canUpdate` returns false though.

You want something like this:

```java
    @Override
    public boolean canUpdate() {
        if (network != null) {
            return network.canRun();
        }

        return false;
    }
```

**Comment by modmuss50** [comment]
Ah nice, thanks for that @raoulvdberge ill get it in soon

**Comment by raoulvdberge** [comment]
@Hail4Gaming  You want the "Relay" in RS. That turns on or off all blocks AFTER the Relay depending on redstone setting.

**Comment by raoulvdberge** [comment]
It's not really your fault though @modmuss50, the behavior changed silently since July 19th due to a bugfix:

https://github.com/raoulvdberge/refinedstorage/commit/addeb00bba1f3b2b4c153dccbf0b2c0384dd24a5#diff-a4cd0b0da86cf618977e510896a10f7b

I forgot this changed network extracting behavior for addons though...

**Comment by Hail4Gaming** [comment]
Hey, I actually found a legit bug, yay! Lol. Thanks for the help guys. I will temporarily set it up with a relay until a fix is made.
