### ISSUE TITLE
Energy use crash [Sponge Issue]

### ISSUE THREAD

**Issue by KappaKiddie** [TechReborn/RebornStorage#33]
https://pastebin.com/JaReHw7F

**Comment by modmuss50** [comment]
Try without sponge...

**Comment by JaSpr** [comment]
We also got two crashes today caused by the same issue, also on a sponge server (running skyfactory 3).

https://gist.github.com/331ba52da12031edd3cb09817968a87b
https://gist.github.com/19c2d4ea3c5ce7e2ce12cbbafef53d2e

I built the multiblock earlier today, and both times it crashed the server immediately after I left my base (teleported to far enough away to despawn my chunks).

I am not able to remove sponge from the server that I play on.

**Comment by KappaKiddie** [comment]
I can't remove Sponge too... But is the same as JaSpr says, when the chunk unload.

**Comment by modmuss50** [comment]
Ok, guess I'm gonna have to install sponge and see what's up then.

**Comment by modmuss50** [comment]
All development has moved to 1.12, it should fix now.
