### ISSUE TITLE
Imput patterns via Hopper/EnderIO cable ...

### ISSUE THREAD

**Issue by Kununa** [TechReborn/RebornStorage#6]
Would be very nice to be able to input patterns with hoppers or cables so it can be automated. Works with the standard crafter that way.

**Comment by modmuss50** [comment]
Yeah that should be possible.

**Comment by Sekwah** [comment]
Don't want to open another thread to suggest/check this. So far this isn't implemented yet, right?

I would suggest allowing us to use RS exporters to automatically send the patterns into the multiblock (since every pattern shares the same itemID).

Either that or do it automatically when connected through cable
