### ISSUE TITLE
Reborn Storage Multiblock does not work - It is Dependant On The RS Crafter Block

### ISSUE THREAD

**Issue by SirTwsted** [TechReborn/RebornStorage#62]
One small problem.
Reborn Storage for some odd reason is dependant on the crafter of Refine Storage in order for it to work
or view the craftable patterns to craft things in Refined Storage System.
When I break the Refined Storage Crafter Block,  You can NOT craft anything within the Reborn Storage System.
When I place BACK the crafter block from Refined Storage, The Reborn Storage system then works fine.
It is dependant on a block when it should not be dependant on this block.
The reason why people get the Reborn Storage System, is to due away with the Refined Storage Crafter block
and its mechanics.

So I ask, Why is Reborn Storage system dependant on the Refined Storage Crafter block in order for it to work properly.??

**Comment by modmuss50** [comment]
Humm, strange that isnt the intended case.

**Comment by SirTwsted** [comment]
I spent 4 1/2 hours taking apart my minecraft mods and fussing with the system in game to eventually figure this out.
My brain hurts now.......

**Comment by raoulvdberge** [comment]
SirTwisted, could we say that was a brain Twister? *badum tss*

**Comment by SirTwsted** [comment]
Hahahaa...  touché   :D

**Comment by modmuss50** [comment]
Humm, I think im going to rewrite part of the mod due to some of theses issues people are having.

**Comment by uecasm** [comment]
Not sure if related, but I didn't want to open a separate issue.  I have a 4x4x4 crafter connected to the controller via a relay, so that I can disable it when I don't want to craft (because its calculated power is ~900 RF/t, which seems a little high; at least it's higher than I can generate right now... maybe I'm trying to use this too early-game, it does seem to require a ridiculous amount of gold to craft).

This worked initially, but after reloading the world there were no craft options in the crafting grid even after turning on the relay.  I had to both break and replace one of the crafter multiblock blocks and remove and replace one of the crafting patterns before it would work.  And then after turning power off again, the crafting options still appeared in the grid, but didn't work.  And still didn't work after turning power back on until I repeated the break and replace.  (When they "didn't work", it still showed the crafting plan and would let me start crafting, but nothing actually happened.)

I don't currently have any base RS crafter blocks in the network, although I might try adding some soon to see if that helps.  (I need some for processing recipes anyway.)
